/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellCatalogoRouteImport } from './routes/_shell.catalogo'
import { Route as ShellComissoesRouteImport } from './routes/_shell.comissoes'
import { Route as ShellConfiguracoesRouteImport } from './routes/_shell.configuracoes'
import { Route as ShellEditorVideoRouteImport } from './routes/_shell.editor-video'
import { Route as ShellFavoritosRouteImport } from './routes/_shell.favoritos'
import { Route as ShellGruposDivulgacaoRouteImport } from './routes/_shell.grupos-divulgacao'
import { Route as ShellIaRouteImport } from './routes/_shell.ia'
import { Route as ShellIntegracoesRouteImport } from './routes/_shell.integracoes'
import { Route as ShellMarketplaceRouteImport } from './routes/_shell.marketplace'
import { Route as ShellMeusLinksRouteImport } from './routes/_shell.meus-links'
import { Route as ShellPedidosRouteImport } from './routes/_shell.pedidos'
import { Route as ShellProdutosRouteImport } from './routes/_shell.produtos'
import { Route as ShellRankingRouteImport } from './routes/_shell.ranking'
import { Route as ApiWebhooksApplyfyRouteImport } from './routes/api.webhooks.applyfy'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCatalogoRoute = ShellCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComissoesRoute = ShellComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracoesRoute = ShellConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEditorVideoRoute = ShellEditorVideoRouteImport.update({
  id: '/editor-video',
  path: '/editor-video',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFavoritosRoute = ShellFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGruposDivulgacaoRoute = ShellGruposDivulgacaoRouteImport.update({
  id: '/grupos-divulgacao',
  path: '/grupos-divulgacao',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIaRoute = ShellIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegracoesRoute = ShellIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMarketplaceRoute = ShellMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeusLinksRoute = ShellMeusLinksRouteImport.update({
  id: '/meus-links',
  path: '/meus-links',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPedidosRoute = ShellPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProdutosRoute = ShellProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRankingRoute = ShellRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => ShellRoute,
} as any)
const ApiWebhooksApplyfyRoute = ApiWebhooksApplyfyRouteImport.update({
  id: '/api/webhooks/applyfy',
  path: '/api/webhooks/applyfy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof ShellCatalogoRoute
  '/comissoes': typeof ShellComissoesRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/editor-video': typeof ShellEditorVideoRoute
  '/favoritos': typeof ShellFavoritosRoute
  '/grupos-divulgacao': typeof ShellGruposDivulgacaoRoute
  '/ia': typeof ShellIaRoute
  '/integracoes': typeof ShellIntegracoesRoute
  '/marketplace': typeof ShellMarketplaceRoute
  '/meus-links': typeof ShellMeusLinksRoute
  '/pedidos': typeof ShellPedidosRoute
  '/produtos': typeof ShellProdutosRoute
  '/ranking': typeof ShellRankingRoute
  '/api/webhooks/applyfy': typeof ApiWebhooksApplyfyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/catalogo': typeof ShellCatalogoRoute
  '/comissoes': typeof ShellComissoesRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/editor-video': typeof ShellEditorVideoRoute
  '/favoritos': typeof ShellFavoritosRoute
  '/grupos-divulgacao': typeof ShellGruposDivulgacaoRoute
  '/ia': typeof ShellIaRoute
  '/integracoes': typeof ShellIntegracoesRoute
  '/marketplace': typeof ShellMarketplaceRoute
  '/meus-links': typeof ShellMeusLinksRoute
  '/pedidos': typeof ShellPedidosRoute
  '/produtos': typeof ShellProdutosRoute
  '/ranking': typeof ShellRankingRoute
  '/': typeof ShellIndexRoute
  '/api/webhooks/applyfy': typeof ApiWebhooksApplyfyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/catalogo': typeof ShellCatalogoRoute
  '/_shell/comissoes': typeof ShellComissoesRoute
  '/_shell/configuracoes': typeof ShellConfiguracoesRoute
  '/_shell/editor-video': typeof ShellEditorVideoRoute
  '/_shell/favoritos': typeof ShellFavoritosRoute
  '/_shell/grupos-divulgacao': typeof ShellGruposDivulgacaoRoute
  '/_shell/ia': typeof ShellIaRoute
  '/_shell/integracoes': typeof ShellIntegracoesRoute
  '/_shell/marketplace': typeof ShellMarketplaceRoute
  '/_shell/meus-links': typeof ShellMeusLinksRoute
  '/_shell/pedidos': typeof ShellPedidosRoute
  '/_shell/produtos': typeof ShellProdutosRoute
  '/_shell/ranking': typeof ShellRankingRoute
  '/_shell/': typeof ShellIndexRoute
  '/api/webhooks/applyfy': typeof ApiWebhooksApplyfyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalogo'
    | '/comissoes'
    | '/configuracoes'
    | '/editor-video'
    | '/favoritos'
    | '/grupos-divulgacao'
    | '/ia'
    | '/integracoes'
    | '/marketplace'
    | '/meus-links'
    | '/pedidos'
    | '/produtos'
    | '/ranking'
    | '/api/webhooks/applyfy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catalogo'
    | '/comissoes'
    | '/configuracoes'
    | '/editor-video'
    | '/favoritos'
    | '/grupos-divulgacao'
    | '/ia'
    | '/integracoes'
    | '/marketplace'
    | '/meus-links'
    | '/pedidos'
    | '/produtos'
    | '/ranking'
    | '/'
    | '/api/webhooks/applyfy'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/catalogo'
    | '/_shell/comissoes'
    | '/_shell/configuracoes'
    | '/_shell/editor-video'
    | '/_shell/favoritos'
    | '/_shell/grupos-divulgacao'
    | '/_shell/ia'
    | '/_shell/integracoes'
    | '/_shell/marketplace'
    | '/_shell/meus-links'
    | '/_shell/pedidos'
    | '/_shell/produtos'
    | '/_shell/ranking'
    | '/_shell/'
    | '/api/webhooks/applyfy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiWebhooksApplyfyRoute: typeof ApiWebhooksApplyfyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/catalogo': {
      id: '/_shell/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof ShellCatalogoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comissoes': {
      id: '/_shell/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ShellComissoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracoes': {
      id: '/_shell/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ShellConfiguracoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/editor-video': {
      id: '/_shell/editor-video'
      path: '/editor-video'
      fullPath: '/editor-video'
      preLoaderRoute: typeof ShellEditorVideoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/favoritos': {
      id: '/_shell/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof ShellFavoritosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/grupos-divulgacao': {
      id: '/_shell/grupos-divulgacao'
      path: '/grupos-divulgacao'
      fullPath: '/grupos-divulgacao'
      preLoaderRoute: typeof ShellGruposDivulgacaoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ia': {
      id: '/_shell/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof ShellIaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integracoes': {
      id: '/_shell/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof ShellIntegracoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marketplace': {
      id: '/_shell/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof ShellMarketplaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meus-links': {
      id: '/_shell/meus-links'
      path: '/meus-links'
      fullPath: '/meus-links'
      preLoaderRoute: typeof ShellMeusLinksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pedidos': {
      id: '/_shell/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof ShellPedidosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/produtos': {
      id: '/_shell/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ShellProdutosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ranking': {
      id: '/_shell/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof ShellRankingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/webhooks/applyfy': {
      id: '/api/webhooks/applyfy'
      path: '/api/webhooks/applyfy'
      fullPath: '/api/webhooks/applyfy'
      preLoaderRoute: typeof ApiWebhooksApplyfyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellCatalogoRoute: typeof ShellCatalogoRoute
  ShellComissoesRoute: typeof ShellComissoesRoute
  ShellConfiguracoesRoute: typeof ShellConfiguracoesRoute
  ShellEditorVideoRoute: typeof ShellEditorVideoRoute
  ShellFavoritosRoute: typeof ShellFavoritosRoute
  ShellGruposDivulgacaoRoute: typeof ShellGruposDivulgacaoRoute
  ShellIaRoute: typeof ShellIaRoute
  ShellIntegracoesRoute: typeof ShellIntegracoesRoute
  ShellMarketplaceRoute: typeof ShellMarketplaceRoute
  ShellMeusLinksRoute: typeof ShellMeusLinksRoute
  ShellPedidosRoute: typeof ShellPedidosRoute
  ShellProdutosRoute: typeof ShellProdutosRoute
  ShellRankingRoute: typeof ShellRankingRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCatalogoRoute: ShellCatalogoRoute,
  ShellComissoesRoute: ShellComissoesRoute,
  ShellConfiguracoesRoute: ShellConfiguracoesRoute,
  ShellEditorVideoRoute: ShellEditorVideoRoute,
  ShellFavoritosRoute: ShellFavoritosRoute,
  ShellGruposDivulgacaoRoute: ShellGruposDivulgacaoRoute,
  ShellIaRoute: ShellIaRoute,
  ShellIntegracoesRoute: ShellIntegracoesRoute,
  ShellMarketplaceRoute: ShellMarketplaceRoute,
  ShellMeusLinksRoute: ShellMeusLinksRoute,
  ShellPedidosRoute: ShellPedidosRoute,
  ShellProdutosRoute: ShellProdutosRoute,
  ShellRankingRoute: ShellRankingRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiWebhooksApplyfyRoute: ApiWebhooksApplyfyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
